### PR TITLE
V0.22.5 cherries

### PR DESCRIPTION
**Pull request by ftl**
**How to categorize this PR?**
/kind enhancement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Part of https://github.com/stackitcloud/ske-base/issues/1609

**Special notes for your reviewer**:
https://github.com/stackitcloud/etcd-druid/pull/19/commits/4589f61cdbf68088e2c6cc55e99008ab88408da9 was removed in consultation with @maboehm

### CODE REVIEW

**Comment by ftl** [comment]
Part of https://github.com/stackitcloud/ske-base/issues/1609

**Review by maboehm — COMMENTED** [review]
/lgtm
but two nits for next time (maybe they need documenting somewhere)
1) We no longer need to change the VERSION file, we calculate the ldflags based on git tags, see https://github.com/stackitcloud/ske-ci-infra/blob/main/config/jobs/etcd-druid/etcd-druid-images.yaml#L36-L40
2) The CODEOWNERS file should be part of the base-branch before opening this PR

**Comment by maboehm** [comment]
/retest
maybe its just a flake...

**Review by maboehm — APPROVED** [review]

**Pull request merged**
