### PR TITLE
V0.22.2 cherry picks

### PR DESCRIPTION
**Pull request by ftl**
**How to categorize this PR?**

/kind enhancement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Part of https://github.com/stackitcloud/ske-base/issues/1410

**Release note**:

```other operator

```

### CODE REVIEW

**Review by robinschneider — APPROVED** [review]

**Review by robinschneider — APPROVED** [review]

**Comment by nschad** [comment]
Test will be fixed with: https://github.com/gardener/etcd-druid/pull/839

**Comment by ftl** [comment]
obsolete

**Pull request closed without merging**
